### ISSUE TITLE
Adding material thickness

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCut#134]
Currently when you add a thickness you get a 2mm thickness, which is kind of random. 
I think it's better to ask for a specific thickness in a dialog or add a new line in the thickness list and put the keyboard focus there so people can add a thickness right away. 
I don't think this has very high priority, but it's good to have it on the todo list.

**Comment by mgmax** [comment]
@peteruithoven Should be fixed, can you please check?

**Comment by mgmax** [comment]
was fixed long ago
