### ISSUE TITLE
Side interface to thin?

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCut#144]
The current version has a small problem on OS X. (I can't think of a reason why I don't see it in Ubuntu).
As you can see in the screenshot the right part stays very small, even after resizing, opening / closing files or restarting VisiCut. This causes the panel menubar? to show only two of it's items and put the third behind a arrow. 
version: 1.6-160-g5a0560d
OS X 10.6.8

![Screen shot 2013-04-15 at 7 44 47 PM](https://f.cloud.github.com/assets/523210/388120/fe053876-a6d1-11e2-8c27-092bce8ee6b0.png)
![Screen shot 2013-04-15 at 9 26 55 PM](https://f.cloud.github.com/assets/523210/388121/fe1b3a54-a6d1-11e2-8105-eef10fbb40ea.png)

**Comment by mgmax** [comment]
Should hopefully be fixed now
