### ISSUE TITLE
App does not start on Mountain Lion 

### ISSUE THREAD

**Issue by t-oster** [t-oster/VisiCut#146]
If you try to start VisiCut on Mountain Lion, you will get a notice like "the app is damaged" and it refuses to start.
Workaround: Start with right-click and Cmd/Alt key and click open, then you can start it.

I am working on a solution, but since I do not have a Mac, this could take a while

**Comment by jnweiger** [comment]
@dercorn please try the right-click cmd workaround? 
It seems to be a signing issue...

**Comment by dercorn** [comment]
@jnweiger  On El Capitan, a right-click makes no difference.

**Comment by jnweiger** [comment]
Oh dear. My hope is that it is still 'just' a signing issue  - and not really a broken package.
@dercorn Can you please check your security settings as described here: https://www.imobie.com/support/mac-os-x-probelms-and-solutions.htm#q4

**Comment by dercorn** [comment]
@t-oster @jnweiger "Allowing apps downloaded from: Anywhere" did the trick!

**Comment by jnweiger** [comment]
Cool! 
I've added some instructions to the releasenotes text on https://github.com/fablabnbg/VisiCut/releases/tag/1.7.0.20151215jw

**Comment by sebastian-schmid** [comment]
Is this still an issue?
I think this can be closed, as described above signing is not really an issue you just have to allow to install the App.

MacOS Package will be working in general with #620

**Comment by dercorn** [comment]
This can be closed.
