### ISSUE TITLE
Online settings repository

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCut#153]
As Thomas suggested in issue #84 it might be interesting to have a online repository of VisicCut settings. This would enable VisiCut, the first time you use it, to propose you download one of these settings. This would take away the step that people need to look up the settings file of the place they are and import it. 

As a Fablab manager myself I think one of the bigger challenge is making it as easy as possible for these places to update their settings file. 

The easiest way would be to give people a link to this website on first time usage. 
The slightly more advanced possibility would be to have a dropdown menu with the available settings which VisiCut can download and import automatically. 
A more future proof way would be to have a list with a filter above it. When you type the list get's filtered by settings that match the text. 

As far as repository I'm afraid I can only help if it's made using Drupal, because I'm no server-side expert, but Drupal seems quite the overkill.

**Comment by matthijskooijman** [comment]
I think this is already implemented long ago? Maybe this issue can be changed? Or are there still improvements to be taken from the above discussion (if so, a more specific new issue might be better for those)?

**Comment by mgmax** [comment]
Reading from online settings is implemented. Writing is still quite difficult -- moving this to #587
