### ISSUE TITLE
Example subfolders only work on OS X

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCut#161]
Working on OS X I made a subfolder in the examples folder to group my test patterns together. But when I export my settings and import my settings on Windows or Ubuntu this folder doesn't show. So while the folder is there, it isn't shown in the examples menu. 
No big problem, but good to know.

**Comment by mgmax** [comment]
closing - not reproduced on Linux. Note that VisiCut must be restarted to see new files, which may be considered a bug.
