### ISSUE TITLE
Severe UI malfunction under Mac OS X 10.7.5

### ISSUE THREAD

**Issue by DavidMenting** [t-oster/VisiCut#171]
Since installing a Java update on OS X 10.7.5 (now Java version 1.6.0_51) Visicut has a severely malfunctioning user interface. It starts empty and only redraws when you resize the window:

![screen shot 2013-07-26 at 16 24 04](https://f.cloud.github.com/assets/869645/862995/ff66d7ce-f5ff-11e2-8329-71d53953efb4.png)

Log entries look like this:

26-07-13 16:27:51,072 JavaApplicationStub: CGContextGetCTM: invalid context 0x0
26-07-13 16:27:51,072 JavaApplicationStub: CGContextSetBaseCTM: invalid context 0x0
26-07-13 16:27:51,072 [0x0-0x38f38f].com.t_oster.visicut.gui.VisicutApp: Jul 26 16:27:51 Davids-MacBook-Air.local JavaApplicationStub[6761] <Error>: CGContextGetCTM: invalid context 0x0
26-07-13 16:27:51,073 [0x0-0x38f38f].com.t_oster.visicut.gui.VisicutApp: Jul 26 16:27:51 Davids-MacBook-Air.local JavaApplicationStub[6761] <Error>: CGContextSetBaseCTM: invalid context 0x0
26-07-13 16:27:51,073 JavaApplicationStub: CGContextGetCTM: invalid context 0x0
26-07-13 16:27:51,073 JavaApplicationStub: CGContextSetBaseCTM: invalid context 0x0
26-07-13 16:27:51,073 [0x0-0x38f38f].com.t_oster.visicut.gui.VisicutApp: Jul 26 16:27:51 Davids-MacBook-Air.local JavaApplicationStub[6761] <Error>: CGContextGetCTM: invalid context 0x0
26-07-13 16:27:51,073 [0x0-0x38f38f].com.t_oster.visicut.gui.VisicutApp: Jul 26 16:27:51 Davids-MacBook-Air.local JavaApplicationStub[6761] <Error>: CGContextSetBaseCTM: invalid context 0x0

The program is unusable. Dialog boxes don't pop up and it is impossible to click buttons.

I might try a downgrade of the installed Java version to see if Visicut starts working normally again.

**Comment by mgmax** [comment]
http://informagen.com/JarBundler/StubFile.html suggests symlinking the java stub.

**Comment by t-oster** [comment]
Looks like a solution. Who can test if this works? I would like the OSX build to work on most OSX versions possible.
