### ISSUE TITLE
Connect split paths

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisiCut#203]
With the "INNER_FIRST" setting and a file consisting of many separate lines that are not connected into one path, the sorting creates lots of idle moves. The real solution would be to connect these paths early in the toolchain, but sometimes this is not possible (e.g. CAD software with DXF export).

The best solution would be to offer cleanup inside visicut before sorting the paths:
- connect non-closed paths where the end points have a distance < epsilon
- remove overlapping line segments distance < epsilon
  epsilon should be something like 0.1mm

An easier workaround would be to change the INNER_FIRST sorting:
- if another path starts very close the current path endpoint, continue with this one (behaviour and most code like in NEAREST)
- else, continue with INNER_FIRST sorting (ignoring the previously joined paths)

Like the code in NEAREST, this needs to check for both the start and the end point of paths, and reverse them when appropriate.

http://www.novopoint.at/styropor-schneiden/lasersoftware/vektoroptimierungstool.html

(This bugreport is mostly a reminder for myself.)

**Comment by mgmax** [comment]
I will not find time to implement this soon, it would be nice if someone else did it.

**Comment by mgmax** [comment]
There might be a problem with wrongly connected paths at three-way intersections, so that inside-out cutting is not preserved. New idea for algorithm:

* (optional: remove duplicate lines)
* for every end of a non-closed path:
  * if there is more than one other open end within a distance of 2*epsilon, do not merge this path, because we have a three-way intersection
  * if there is one other open end within a distance of 1*epsilon, join these paths, maybe by inserting a short line segment
* (optional: reverse paths for speed optimisation)

with epsilon something smaller than half the cutting width, like 0.1mm

**Comment by jnweiger** [comment]
I've done something similar as an inkscape plugin. Maybe thatt is the *real solution* you were looking for?

http://github.com/fablabnbg/inkscape-chain-path

**Comment by mgmax** [comment]
I think this is too early in the process, and so it can't be used for DXF files from CAD software where the issue is particularly annoying.

**Comment by jnweiger** [comment]
It was actually written for fixing DXF. My happy users do this:

Dxf -> inkscape -> visicut.

**Comment by McNugget6750** [comment]
@jnweiger The extension you posted here about a year ago solves problems with DXF files that many people have! I will integrate it into my laser cutter tool chain and I hope it becomes part of VisiCut at some point! The python script is so short and it just connects the ends of each line where applicable... You need more publicity with this! Thank you!
