### ISSUE TITLE
OS X Yosemite Java SE 6-Runtime-Version issue

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCut#210]
After upgrading OS X to Yosemite Java is removed. Users that try to run Visicut get a popup informing that Visicut requires "Java SE 6-Runtime-Version". 
Installing Java from the following pages doesn't seem to help:
- https://www.java.com/en/download/index.jsp
- http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

I'm hoping the following will work:
http://support.apple.com/kb/DL1572

I'll update this issue when I know more.

**Comment by t-oster** [comment]
Well... where should we integrate this? Does anybody know other popular Java apps on OS X? How do they solve the issue?

**Comment by mgmax** [comment]
Closing because the report refers to a very old version. Feel free to reply if the bug also happens in a recent version of VisiCut with Java >= 9.
