### ISSUE TITLE
Asks to download settings on first startup? 

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCut#218]
If I understand the following pull request correctly VisiCut should suggest to download default settings on first startup. 
https://github.com/t-oster/VisiCut/pull/212
I was trying to simulate this by removing the *.visicut* folder in my home folder, but this didn't work. Is there another way to simulate a first boot? I'd like to the check the experience.

**Comment by mgmax** [comment]
for me, "rm -r ~/visicut" works (just tried in a debian lenny VM with 
newest visicut deb package)

**Comment by peteruithoven** [comment]
Nice! Don't know what I did wrong previously, but removing ~/.visicut worked this time (on OS X).
