### ISSUE TITLE
facebook integration

### ISSUE THREAD

**Issue by renebohne** [t-oster/VisiCut#223]
The same group of students that is working on the thingiverse integration (issue 222), will also provide basic facebook functionality:
- facebook login
- share projects on facebook

it is not clear, how users will benefit from this feature, but maybe other people on github have some ideas :)

**Comment by tur0kk** [comment]
Current status:
- facebook login and profile information
- use camera to take a photo
- add a description
- publishing of a facebook post with the taken image and the description
- FabLab location is added to the post
![facebook](https://cloud.githubusercontent.com/assets/5971442/5723077/8e2193a4-9b41-11e4-927e-282ae58f5b98.PNG)

**Comment by renebohne** [comment]
is the fab lab location a new setting in VisiCut? Sounds like a nice general setting to me.

**Comment by tur0kk** [comment]
New update:
- We added VisiCam as an alternative source to the webcam (selectable by radio buttons)
- FabLab Facebook Location Id now is a general setting

**Comment by renebohne** [comment]
the students also created a tutorial video for this feature:
http://youtu.be/MxeHqAg4TIs

**Comment by t-oster** [comment]
Please clean-up the code and commit history before creating a pull-request.
