### ISSUE TITLE
Improve Windows tip

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCut#224]
Currently the following warning is shown on the windows tab on the downloads page: 
> If you use Windows 7 or 8, you might face the problem, that the installer does not detect the Java Runtime Environment.
> Please use the Platform independent ZIP version, until this error is fixed. 

I would like to suggest adding which file in the zip needs to be opened, something like: 
> If you use Windows 7 or 8, you might face the problem, that the installer does not detect the Java Runtime Environment.
> Please use the Platform independent ZIP version, until this error is fixed. Open the .jar file with the *Java runtime* / *Java(TM) Platforms SE binary*.

**Comment by t-oster** [comment]
done.
