### ISSUE TITLE
Move all Information to new GitHub page

### ISSUE THREAD

**Issue by t-oster** [t-oster/VisiCut#233]
I'd like to move from http://hci.rwth-aachen.de/visicut to the new Github page http://t-oster.github.io/VisiCut/.

Whoever wants to contribute, just create pull-requests on the branch "gh-pages".
I would recommend to clone this into a new repository, since it has nothing in common with the master or develop branch: 

```
git clone https://github.com/t-oster/VisiCut.git -b gh-pages --single-branch VisiCutPage
```

(for write access, replace the URL by your forked git-url.

**Comment by mgmax** [comment]
I like the wiki because it is easier to edit. Can't we move as as possible there and only link from the homepage?

**Comment by t-oster** [comment]
Of cause. All information, where people might want to change should be in the Wiki. I am more talking about the general project page, as well as "moderated" content like announcements and the download-page.

**Comment by t-oster** [comment]
done.
