### ISSUE TITLE
remove splashscreen

### ISSUE THREAD

**Issue by sedrubal** [t-oster/VisiCut#267]
I don't like splashscreens ;) they're slowing down the workflow

**Comment by t-oster** [comment]
I am not sure if it slows down the start. I think the JVM takes some time to start so it shows the user that something is happening. Will have to do some timing tests.

-------- Ursprüngliche Nachricht --------
Von: sedrubal <notifications@github.com> 
Datum:26.04.2015  03:58  (GMT+01:00) 
An: t-oster/VisiCut <VisiCut@noreply.github.com> 
Betreff: [VisiCut] remove splashscreen (#267) 

I don't like splashscreens ;) they slowing down the workflow

**Comment by sedrubal** [comment]
Thank you ;)

**Comment by renebohne** [comment]
solution: never close VisiCut. But close this issue :)

**Comment by mgmax** [comment]
The splash screen does not slow down the start. The JVM is really that slow.
