### ISSUE TITLE
Settings Tab does not update when selected file (from dropdownbox) changed

### ISSUE THREAD

**Issue by renebohne** [t-oster/VisiCut#270]
The Settings Tab does not update when we select a different file. In this example, one file uses a "cut everything" profile and the second file uses a "mark everything" profile. 
Here is a video that should explain the problem, notice the words "mark" and "cut":
https://youtu.be/xdKuP0LHYX0

**Comment by mgmax** [comment]
As far as I tested, the issue is gone. Was probably "accidentally" fixed some time ago.
