### ISSUE TITLE
Does VisiCut support marlin?

### ISSUE THREAD

**Issue by quillford** [t-oster/VisiCut#283]
I am using [this fork](https://github.com/TurnkeyTyranny/buildlog-lasercutter-marlin) of Marlin.

**Comment by t-oster** [comment]
Hi. Not yet, but don't hesitate to develop a driver for it. instructions: 

SetUp:
- https://github.com/t-oster/VisiCut/wiki/Development:-Getting-started

Sample Driver:
- https://github.com/t-oster/LibLaserCut/blob/develop/src/com/t_oster/liblasercut/drivers/SampleDriver.java

**Comment by t-oster** [comment]
Should be easy with the generic gcode driver. Have a look at https://github.com/t-oster/LibLaserCut/pull/23
