### ISSUE TITLE
Prevent multiple equal messages?

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCut#294]
For issues like #291 it might be interesting to prevent the same error to keep stacking up. Maybe we can implement the same behavior as Firefox's web console? This increments a counter instead of repeating the message. 
![screen shot 2015-08-10 at 07 47 21](https://cloud.githubusercontent.com/assets/523210/9160057/1ce24dea-3f34-11e5-90cc-8c3615ebe718.png)

**Comment by sedrubal** [comment]
:+1:
