### ISSUE TITLE
Visicut windows 10 - Unable to see time to cut

### ISSUE THREAD

**Issue by nikhilbhansali** [t-oster/VisiCut#305]
Hey guys,
Sorry if this question is obvious, but I am unable to get time to cut when I load a DXF file onto Visicut. Now, I don't own a laser cutting machine, but we need time to cut to build an online tool we are working on. Basically we want to calculate the price when a person uploads a file onto our site, and time is the parameter which the cost is dependent on.

So please please tell me how to calculate the time to cut.
Thanks
Nikhil

**Comment by t-oster** [comment]
Hi. The time calculation is done in the lasercutter-driver. The only driver, which supports it right now is the Epilog one. See this methods: https://github.com/t-oster/LibLaserCut/blob/develop/src/com/t_oster/liblasercut/drivers/EpilogCutter.java#L886.

If you select this driver (e.g. in the FabLab-Aachen settings), you should be able to calculate time.
