### ISSUE TITLE
Export Laser Code opens open file dialog

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCut#322]
@mrzl, the `Export Laser Code...` feature on OS X seems to open a Open file dialog:
![screen shot 2015-12-17 at 00 09 24](https://cloud.githubusercontent.com/assets/523210/11856700/1cab9230-a453-11e5-8894-5f83a409cbeb.png)
When I select an existing file and "open" it it does write the simplecode to it.

**Comment by mrzl** [comment]
Whoops, sure- that's better :]
