### ISSUE TITLE
shell script wrapper changes working directory

### ISSUE THREAD

**Issue by hexwab** [t-oster/VisiCut#324]
The scripts in VisiCut/distribute/files/ change the current working directory before the program proper is executed. This causes problems when passing relative pathnames on the command line:

    [~]% ls -l dodec3p.svg
    -rw-r--r-- 1 HEx HEx 5272 Dec  1 22:18 dodec3p.svg
    [~]% visicut dodec3p.svg
    Error parsing gtk-icon-sizes string: ''
    Can not find file: dodec3p.svg

**Comment by t-oster** [comment]
hmm. I am not sure if java needs the working directory to be correct. If you want, feel free to experiment and submit a pull request.

**Comment by t-oster** [comment]
nevermind
