### ISSUE TITLE
Thingiverse Integration

### ISSUE THREAD

**Issue by tur0kk** [t-oster/VisiCut#328]
I submitted the Thingiverse app for approval, but they requested for reviewing it:
a version of VisiCut for OSX with the Thingiverse integration.

It a ready to run build version available with the Thingiverse integration?

**Comment by t-oster** [comment]
Just use the current platform independent zip Version from the develop branch
-- 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by tur0kk** [comment]
Thingiverse app is approved now, so anyone can use the Thingiverse integration.

**Comment by t-oster** [comment]
So this can be closed?

**Comment by tur0kk** [comment]
Yes
