### ISSUE TITLE
download.visicut.org is down?

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCut#333]
http://download.visicut.org/ seems down?

**Comment by t-oster** [comment]
Yep. Use https://github.com/t-oster/VisiCut/releases in the meantime, but I am working on a solution...

**Comment by peteruithoven** [comment]
Ah thanks! We'll a note put it on our website.

**Comment by t-oster** [comment]
It's up again and should now be more stable.

**Comment by peteruithoven** [comment]
Awesome, thanks!
