### ISSUE TITLE
Engraving: Exporting of Laser Code(G-code) does not work

### ISSUE THREAD

**Issue by miszr** [t-oster/VisiCut#340]
When you try to export G-code for engraving, nothing is written except for the start and end gcodes. Tested newest development branch.

**Comment by t-oster** [comment]
Do you have selected a mapping?

**Comment by koswix** [comment]
I also experience this issue on latest build. Using netbeans it seems it doesn't generate the G-Code until you hit SEND, exporting just gives you the pre- and post-job codes from the settings file. Happens with either Engrave selected or Engrave 3D.
