### ISSUE TITLE
Update px unit size for files created by Inkscape >0.92

### ISSUE THREAD

**Issue by pelrun** [t-oster/VisiCut#347]
When investigating #346 it became clear that we're going to have an issue with documents produced by Inkscape 0.92 and later, because the px unit is moving from 90dpi to 96dpi. The original value was due to a typo in the CSS2 standard that was fixed in an errata, but Inkscape used the incorrect value. It's finally been fixed in the development version.

Since Illustrator and other SVG producers use different sizes for the px unit, Visicut tries to determine the creator of an imported file and set the dpi appropriately. We'll soon need to distinguish between SVGs from Inkscape <=0.91 and Inkscape >=0.92 for this to work consistently. Also, the fallback value is 90dpi which seems like it should also be changed to 96 since non-Inkscape producers are more likely to use the latter value than the former.

**Comment by jnweiger** [comment]
Start inkscape0.92 with out loading an svg file, draw some objects, and send to an extension.
The svg sent has no inkscape:version element.
Save as box.svg, then send to an extension, the svg contains 'inkscape:version="0.92.1 unknown" sodipodi:docname="box.svg">'

As an inkscape extension, we cannot know if we should assume 96 or 90 dpi, unless we find a 'sodipodi:docname' element. 
If we find sodipodi:docname, but we don't find inkscape:version, we can assume 90. 
If we find both, we can assume 96.

Looks like a bad inkscape bug to me!
