### ISSUE TITLE
File handle appears to be left open when exporting laser code

### ISSUE THREAD

**Issue by tealvince** [t-oster/VisiCut#355]
When using the "Export laser code" menu to save gcode (generated for a smoothieboard) to a file under Windows, the write handle to the file appears to be left open. Multiple files can be created, but they all appear 0 bytes in size until Visicut is closed.

**Comment by pelrun** [comment]
I've seen that behaviour when I try to save directly to the Smoothieboard USB drive, but assumed it was more of a problem on the smoothie side. I'll have another look at it.

**Comment by pelrun** [comment]
@tealvince, did you get an opportunity to test this? It'd be good to close it off.

**Comment by pelrun** [comment]
@t-oster, you can close this.
