### ISSUE TITLE
Duplicate element then non-drag reposition gets confused

### ISSUE THREAD

**Issue by pelrun** [t-oster/VisiCut#374]
Was making several copies of a design by right-clicking and selecting "duplicate", then modifying the fields in the position tab. Things then got a bit screwy, with the original cut vanishing, and the copy not being selectable, and selecting via the file dropdown didn't produce the expected result either. So some internal state is getting confused.

If I duplicate the design and then drag the copy away, then everything works properly and I can reposition both copies with the position tab without any problems.

**Comment by mgmax** [comment]
How to reproduce this bug:
- Load file (e.g. circle-20mm-red.svg from the examples)
- Drag to x=100mm (exact value does not matter)
- right-click
- duplicate
- do not drag, but go to the "position tab", set x=200mm, press enter key

Expected:
- first file is at x=100mm, second file at x=200mm

Actual result:
- first file disappears from the preview, but can somehow still be selected from the preview.

**Comment by cdemeijer** [comment]
My first guess was that it is related to GraphicSet.clone method. I'm totally new to VisiCut and just messing with the code for now.
Although I seem to have it fixed locally, I'm not (at all) sure that I didn't break the code somewhere else.
Will clean up and test more tonight.

**Comment by cdemeijer** [comment]
PR submitted. Hope that submitting a PR for the master branch is the correct way. I couldn't find the develop branch mentioned in the developers documentation :/

**Comment by t-oster** [comment]
Yes, we switched to a more agile way with master being the latest version and instant release. Thanks for the PR
