### ISSUE TITLE
potrace

### ISSUE THREAD

**Issue by brains12345** [t-oster/VisiCut#383]
Sorry but I am a dummy with some installations.
will you please describe how I can use Potrace with visicut. I have a graphic on the screen and a right click says I can vectorise it, the a window requesting Potrace installation apeers. I have downloaded Potrace but after that i am lost.
Thank you

**Comment by t-oster** [comment]
Hi, which operating system are you using, where is VisiCut installed, where ist Potrace installed (and which version) and what are the contents of your PATH variable?

**Comment by brains12345** [comment]
visicut is installed in programmes folder. potrace in my documents folder. Path variable I do not understand!
regards

**Comment by t-oster** [comment]
so I assume windows.... could you try to copy the potrace.exe into the visicut folder?

**Comment by brains12345** [comment]
will try, thank you

**Comment by brains12345** [comment]
![image](https://cloud.githubusercontent.com/assets/16066776/18911184/e067c25c-857b-11e6-913f-95c1897f65e5.png)
sorry That did not work!

**Comment by pelrun** [comment]
I just tested putting potrace.exe and mkbitmap.exe in the Visicut folder and it found them fine.

Did you download the correct Windows version of Potrace?

**Comment by brains12345** [comment]
I think so win 10 64 bit, I will check again

**Comment by brains12345** [comment]
cracked it, many thanks, downloaded it from microsoft
