### ISSUE TITLE
GRBL response failure

### ISSUE THREAD

**Issue by iceblu3710** [t-oster/VisiCut#391]
I notice in the grbl driver you remove the response string from the config screen but the generic driver still checks the response.

generic driver:  

`protected String identificationLine = "Grbl";`

grbl driver:

`result.remove(GenericGcodeDriver.SETTING_IDENTIFICATION_STRING);`

The 0.9 release of GRBL now responds `Grbl 0.9j ['$' for help]` so the system fails immediately when trying to send the job. Would be nice to just leave this as a configurable option when setting up the driver.

**Comment by iceblu3710** [comment]
Moved to `t-oster/LibLaserCut`

**Comment by mgmax** [comment]
was fixed in https://github.com/t-oster/LibLaserCut/pull/69
