### ISSUE TITLE
"VisiCut is damaged and can’t be opened." Error in MacOS Sierra

### ISSUE THREAD

**Issue by agreiner29** [t-oster/VisiCut#393]
The "allow applications from anywhere" is not available in MacOS Sierra. There is a workaround to enable it, but it is inconvenient.

**Comment by pelrun** [comment]
We're aware of this issue, see #146.

**Comment by jsphpl** [comment]
Check this answer for a workaround: http://apple.stackexchange.com/a/102358

**Comment by t-oster** [comment]
i.e. try running `xattr -rc /Volumes/path/to/VisiCut.app` in your terminal

**Comment by t-oster** [comment]
(closing this as duplicate of #146)
