### ISSUE TITLE
Often have to import file twice, will not import on first try

### ISSUE THREAD

**Issue by agreiner29** [t-oster/VisiCut#394]
Nothing happens the first time I import a document. I often have to import it twice.

**Comment by pelrun** [comment]
I can't replicate that here. Can you give us more information? (platform, file attempted, visicut version etc)

**Comment by mgmax** [comment]
This should be fixed by commit a7d9fff723e6aa2dcc6e78a1080e4ee3a786cb58.

Please close this issue if it is fixed for you, otherwise please provide more details.

**Comment by mgmax** [comment]
@t-oster  could you please close the issue, as the submitter does not respond and the bug has most certainly been fixed?
