### ISSUE TITLE
Build Requirements

### ISSUE THREAD

**Issue by iceblu3710** [t-oster/VisiCut#395]
I get errors about missing dependencies, I add then and get some more, over and over...

Do you have a complete list of requirements for a vanilla build environment? I would like to build in a VM.

**Comment by pelrun** [comment]
They should already be included in the lib directories for visicut and liblasercut.

**Comment by t-oster** [comment]
If you mean stuff for building the OS specific packages,i have a docker container with everything.
I will post the Dockerfile tomorrow

**Comment by iceblu3710** [comment]
A docker container would be fantastic thanks.

**Comment by t-oster** [comment]
Hi,

this is a hacky version, I am using, but it works for me. Feel free to polish it and create a github project, if you think it is ready for other people to use.

It is based on ArchLinux but there are some dependencies which I needed to include separately.

[visicutbuildservice.zip](https://github.com/t-oster/VisiCut/files/630437/visicutbuildservice.zip)

**Comment by mgmax** [comment]
Thomas, can you please create a Github repo anyways? Published code is always better than unpublished code.

**Comment by t-oster** [comment]
here you are https://github.com/t-oster/VisicutBuilder

**Comment by t-oster** [comment]
I guess this is solved by the image....
