### ISSUE TITLE
Is the UTF-8 encoding supported?

### ISSUE THREAD

**Issue by Richmond96** [t-oster/VisiCut#405]
Hi,

I'm localizing to Italian your software for @WakenMakeFabLab. When I launch your program it looks like the UTF-8 encoding isn't supported.

Is that right or ther's a way to enabling UTF-8 encodign?

Thanks
Riccardo

**Comment by t-oster** [comment]
well IMHO java and swing should be UTF-8 by default. How are you making the translation? Are you following https://github.com/t-oster/VisiCut/wiki/How-to-translate-VisiCut ?

**Comment by Richmond96** [comment]
Yeah, I'm following your instructions, but I launch the project with Netbeans and I notice that there's a problem with accented characters. 
I also checked that the UTF-8 encoding was enable for the project and I've tried with other project and they didn't have any problem.
When I launch yours, the display of accented characters is incorrect

**Comment by t-oster** [comment]
Could you post the utf8 encoded Translation Files, so I can Check this?

**Comment by Richmond96** [comment]
Sorry, I used the native form (à,è,ì,ò,ù) to insert the accented characters.
Instead using the corresponding ascii code there no display problem for the accented characters
