### ISSUE TITLE
SingleInstance vs. multiple X display

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisiCut#41]
Hi,

please only do singleInstance once per X11 $DISPLAY.

max@max-thinkpad:~$ ssh -X localhost 'echo $DISPLAY; visicut' &
localhost:10.0
(visicut starts normally)

(while first session is running:)
max@max-thinkpad:~$ ssh -X localhost 'echo $DISPLAY; visicut'
localhost:11.0
(visicut exits immediately because it notices the other instance)

This needs changes in the single-instance java code and in the inkscape plugin. Ugly workaround: Just convert the display string to some number (10.0 -> 100) and add this to the port number?

Thanks

Max

**Comment by sedrubal** [comment]
Why is visicut a single instance application?!? That's really not practicable: One user is laser cutting his job, another wants to prepare his job on the same machine but the first one needs to change something on his job an so on.

What's the problem on having multiple instances holding multiple files?

**Comment by t-oster** [comment]
VisiCut is not a single instance application, but if you start it with the same "--singleinstanceport" parameter, it tries to find a running instance. This is for enabling a workflow like
* Create a drawing in Inkscape
* Select some parts, fire up visicut through the plugin
* select some other parts, add them to the current drawing in VisiCut

**Comment by t-oster** [comment]
(also in my opinion if two users are working on the same machine they should use different user accounts). But still, just call VisiCut with differnt singleinstance paramters as often as you like

**Comment by sedrubal** [comment]
ah ok... thanks
