### ISSUE TITLE
visicut logo spot on chinese hardware

### ISSUE THREAD

**Issue by clemclemmm** [t-oster/VisiCut#423]
not an issue, 
i just spot the visicut logo on the touchpanel of Ruida laser controller : 
https://www.picclickimg.com/d/w1600/pict/122711903583_/Ruida-RDC6344G-7-Touch-Panel-Co2-Laser-DSP.jpg 
so it's was just fun to tell you ;-)

**Comment by clemclemmm** [comment]
that's all.

**Comment by t-oster** [comment]
Well actually I took it from the icon pack "Pry System" by "Jonas Rask Design" which is licensed under "Freeware Non-commercial"

**Comment by t-oster** [comment]
But still a Fun fact :) thanks for Sharing
