### ISSUE TITLE
text in splash screen broken

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisiCut#430]
Something is missing on the official buildserver: The text in the splash screen is only shown as squares, like □□□□□□□ □□□.

**Comment by t-oster** [comment]
hmm... i guess it's missing a font in the https://gitlab.com/t-oster/visicutbuildservice docker-container... I will look into it.

**Comment by renebohne** [comment]
The splash screen is still broken, tested in 1.8.23 screenshot attached.
![screen shot 2018-04-29 at 13 27 11](https://user-images.githubusercontent.com/671105/39406088-45ac7caa-4bb1-11e8-99f3-cf24ca187e68.png)

**Comment by mgmax** [comment]
@t-oster could you try to add the ttf-freefont package to your Dockerfile?

**Comment by t-oster** [comment]
well.. if I rebuild the container with the latest arch-linux baseimage, it does not work anymore. I guess the checkinstall command has to be updated... 
Is this a wild guess or can you confirm that the ttf-freefont package would solve it so it is worth fixing?

**Comment by t-oster** [comment]
fixed thanks to @mgmax
