### ISSUE TITLE
file won't load in Visicut version 1.8-6 on Mac

### ISSUE THREAD

**Issue by zebulong** [t-oster/VisiCut#438]
1.8-5 works fine, but 1.8-6 will not load a file.  Both using the file button and dragging/dropping a file hangs up the progress bar and nothing loads.  Using Mac OS High Sierra 10.13.3

**Comment by mgmax** [comment]
I don't see any possible reason in the code. Can you try it on another Mac to make sure it's not special to your system?

**Comment by zebulong** [comment]
oh, how interesting.  it loads on my other Mac!    any idea of what could be blocking the run of this app on my other mac machine???

I really like visicut- thanks for making it and if i can get the latest version to run, i’ll be even happier.   thanks if you have any suggestion.   maybe i should use app. delete to remove the older version???

james

**Comment by hillct** [comment]
Is that an issue other than the documented GateKeeper / Application signature problem?

**Comment by zebulong** [comment]
Yes, separate issue.    The program opens but it won't let me load a file.    But no worries, because the latest version that was just posted seems to work fine!        Thanks!
  
  
  

  
  
  
  
  
>

**Comment by renebohne** [comment]
zebulong, so this ticket can be closed? Which version solved your problem?

**Comment by zebulong** [comment]
1.8-11 seems to work ok, I just downloaded the latest one and it seems to be ok
Thanks!
