### ISSUE TITLE
Version number inconsistent?

### ISSUE THREAD

**Issue by jnweiger** [t-oster/VisiCut#440]
In the 1.8 tag this file still says 1.7, is that intentional? :

https://github.com/t-oster/VisiCut/blob/280209132c6e630217aaac84fa4d9713e32a00cd/src/com/t_oster/visicut/gui/resources/VisicutApp.properties#L5

**Comment by t-oster** [comment]
This field is updated by the build-server on every build to match the current git-tag. So no, this is not intentional, but also not important for the released builds. Feel free to update.

**Comment by t-oster** [comment]
(see https://github.com/t-oster/VisicutBuilder/blob/master/build.sh#L46)
