### ISSUE TITLE
Forecast of Lasercut-duration shows wrong values

### ISSUE THREAD

**Issue by Nos-** [t-oster/VisiCut#449]
Hi. I lasered several things on an Epilog-Laser while measuring the time it takes. The prediction is usually far from the real duration.
Maybe there are some device dependant parameters for example the acceleration of the lasercutters mechanic.

**Comment by t-oster** [comment]
Here is where its calculated https://github.com/t-oster/LibLaserCut/blob/dedf96d2aaec89d1ffe61d67242420ff0fb709c3/src/com/t_oster/liblasercut/drivers/EpilogCutter.java#L901

**Comment by mgmax** [comment]
Probably fixed, as it was recently rewritten. There were some bugs in the logic that could generate negative times.
