### ISSUE TITLE
Lasercutter settings are not stored in VisiCut 1.8.22

### ISSUE THREAD

**Issue by stefan-sch** [t-oster/VisiCut#453]
In Visicut 1.8..22 under Optionen / Lasercutter verwalten ... new values for Hostname, Port, BedWith etc. are not stored (at least here with Win10, 64 Bit). Values are set back to default values after saving and re-opening the dialog.
No problem under VisiCut 1.8.21.

**Comment by t-oster** [comment]
Sorry, was my mistake. Will be fixed in a minute.

**Comment by t-oster** [comment]
please use 1.8.23
