### ISSUE TITLE
add setting for FabLab Chemillé en Anjou

### ISSUE THREAD

**Issue by bocal-chemille** [t-oster/VisiCut#459]
Hello, can you put this setting ? 
choices.put("France, Boc@l: FabLab Chemillé en Anjou", "https://github.com/bocal-chemille/Visicut/blob/master/config_laser_bocal.vcsettings");

Thanks

**Comment by mgmax** [comment]
to copy my comment from another place: I think the name should be "Country, city: Name of FabLab". I don't think the city is named "Boc@l".  (I think we made an error with HAUM, but all other labs are in this way, and we should keep the list consistent.)


By the way, I think that the list should be alphabetically sorted, whereas currently it is only sorted by country.

**Comment by bocal-chemille** [comment]
Ok sorry !!! 

I think country sorted it's ok for the moment :), by with 300 entry ... i don't know ! 
Country France, 
City : Chemillé en Anjou
Name of Fablab :  Fablab Le Boc@l
Settings : https://github.com/bocal-chemille/Visicut/blob/master/config_laser_bocal.vcsettings

this is better : 
choices.put("France,  Chemillé en Anjou : FabLab le Boc@l",** "https://github.com/bocal-chemille/Visicut/blob/master/config_laser_bocal.vcsettings");


thaks a lot !
