### ISSUE TITLE
default HPGL dpi don't match the standard

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisiCut#463]
Wikipedia says that HPGL is 1016 units-per-inch, but we use 1000 as default [here](https://github.com/t-oster/LibLaserCut/blob/f08f326558b8cb528768d737945cd42396a2a4a6/src/com/t_oster/liblasercut/drivers/GoldCutHPGL.java#L529).

@jnweiger Is it intentional that Goldcut uses 1000 or is it okay to change the default to 1016?

Quote from Wikipedia:
> The coordinate system was based on the smallest units one of the HP plotters could support, and was set to 25 µm (i.e. 40 units per millimeter, 1016 per inch)

(edit: sorry, this report should have gone to LibLaserCut, but let's just keep it here and quickly solve it before creating too much noise by copying it.)

**Comment by jnweiger** [comment]
Goldcut should most probably also use 1016 dpi. I was not aware that the spec is actually metric. Nice!
Good catch!
