### ISSUE TITLE
1.8-29 will not even start on MacOS High Sierra

### ISSUE THREAD

**Issue by LenoreHorner** [t-oster/VisiCut#465]
Downloaded 1.8-29 (specifically VisiCutMac-1.8-29-geaadcbe3.zip).  Double-clicked zip file.  Double-clicked resulting VisiCut.app file.  Error message says need Java 6E legacy (still!?).  Clicked more info which took me to the website to get that installer.  Installed that.  Installation claimed to be successful.  Double-clicked VisiCut.app again. This time I was told file is damaged and can't be opened and should be trashed.

**Comment by LenoreHorner** [comment]
I can use the platform independent version but ONLY by clicking directly on the .jar file (not the file VisiCut.MacOS because the OS doesn't know what to use to open that) AND then going to preferences and telling the security panel it is ok to open this from an unsigned developer.

**Comment by t-oster** [comment]
Yes OSX is pretty restrictive. Any help appreciated.

**Comment by LenoreHorner** [comment]
I'm not sure what help you're looking for.  Here's a slightly more detailed version of what I noted above works. 

Unless the Mac version works for some reasonably recent MacOS versions, I think you’d be better off not posting it at all and just telling Mac users to work from the generic version.  That works fine if you click on the .jar file directly and doesn’t require a deprecated version of java.  It would help if that .jar file didn’t show up as know unknown developer but as long as the user has administrative privileges, that can be gotten around relatively easily and only has to be done once.  Don’t bother with the .MacOS file because that extension isn’t recognized and you have to know enough to say "open with" and then force all apps not just recommended ones to show and then choose Terminal from the Utilities folder.

**Comment by t-oster** [comment]
If you Start from the jar,you may not geht enough memory for big engravings. Tue .MacOs file is a hash script eh ich adds the memory parameters.
We need an OSX developer who can package the APP including Java, sign it and maybe add to the app store

**Comment by LenoreHorner** [comment]
Would those memory errors also prevent VisiCut from connecting to the Helix via USB?  Because I got stuck there.  I can try running the .MacOS file and see if that fixes my connection issue.  I might be able to figure out the packaging thing but I don't think the signature and access to the app store are free.  I might be wrong.

**Comment by t-oster** [comment]
USB is not supported in the Epilog driver,you need Ethernet.

**Comment by LenoreHorner** [comment]
Good to know.  Seems and odd choice with most laptops having no ethernet connection (except via USB converter).  Is the assumption that the cutter is hardwired and then spoken to wirelessly over LAN?

**Comment by t-oster** [comment]
Well it was just easier to reverse engineer the Ethernet Version and platform independent USB communication is not easy. However since visicut is open source feel free to add it.
Most lasercutters are in labs with multiple PCs connted via LAN OR wifi

**Comment by LenoreHorner** [comment]
So how does one tell VisiCut what address to look for the laser cutter at?  That doesn't seem to be in the instructions and I don't find a menu item for it.

**Comment by t-oster** [comment]
Go to settings manage lasercutters

**Comment by LenoreHorner** [comment]
Ok.  I found the menu Options -> Laser cutters -> (click on controls icon).  It wasn't both an IP and a port number.  Is only the IP relevant if I'm using ethernet? If not, what port do I need to set?  It pops up with 500.

**Comment by t-oster** [comment]
I think 515 is the epilog default port

**Comment by LenoreHorner** [comment]
Thanks.  I'll try that tomorrow.

So far, I've been able to fix your MacOS script so it is dble-clickable, but I haven't been able to create a dble-clickable application bundle that will stay running (it starts, but croaks after the splash screen).  I think code-signing and writing the USB code are probably more than I have time to learn.

**Comment by LenoreHorner** [comment]
I finally realized what the singleinstanceport part of the script was trying to do.  Since it wasn't working on MacOS (High Sierra) anyhow, I removed that part of the command and now VisiCut can be started by double-clicking an application icon.  Right now it's just a generic icon.  I also had to alter visicut_export.py in inkscape_extension to reflect the correct path in the bundle.
[VisiCutTest.app.zip](https://github.com/t-oster/VisiCut/files/2102189/VisiCutTest.app.zip)
The app bundle doesn't have to be called VisiCutTest.app; nothing depends on that name the way I have things set up.  So this looks a bit nicer to Mac users and the cost of you having to create a second directory structure and a second version of visicut_export.py for the app bundle versus the cross-platform version.  You could also just use the following as the MacOS script in the cross-platform version. 
[VisiCut-MacOS.command.zip](https://github.com/t-oster/VisiCut/files/2102232/VisiCut-MacOS.command.zip)

Users will still have to go through the System preferences step for opening unsigned code, but that only has to happen once.

**Comment by LenoreHorner** [comment]
Sorry. I didn't test enough.  The .app opens VisiCut from Inkscape but nothing gets sent to Visicut from Inkscape.  I have no idea why changing the path to the file should change what is sent down that path.

**Comment by LenoreHorner** [comment]
Same problem occurs with the renamed script.  MacOS users can use the cross-platform version by ctrl-click the \verb!.MacOS! file.
				\item Choose \verb!Get Info!.
				\item  Use the \verb!Open With! drop down to select \verb!Other!.  
				\item Switch to \verb!All Applications! and choose \verb!Terminal! from the \verb!Utilities! folder and then when it fails to run b/c it's unsigned, saying ok anyhow in the System Preferences.  After this, dble-clicking the script SHOULD work. 

However, I still can't actually talk to our Epilog Helix cutter.  I have a cross-over ethernet cable connected via USB-ethernet adapter to my laptop.  I have tried the default IP (10.0.0.1) and the factory IP (which I did check our cutter is still set to of 192.168.003.004).  Both connections time out.  I've left the port set to the default of 515.  If I go into Network Setting ins System Preferences and set my ethernet adapter to be 192.168.3.3, then I get Error \\ Exception: Timeout.  All other configurations I have tried give instead Error \\ Connection timeout. Please see if the Lasercutter is switched on and connected to the network.  \\ SocketTimeoutException: connection timed out

I know there's a lab that claims to be using your software in an all-Mac lab, but I have no way of contacting them so I don't know where to go to figure out this connection issue.

**Comment by t-oster** [comment]
If you are using crossover you dont have DHCP. You must set static IPs on both Ends. Try with ping If you can reach the cutter

**Comment by LenoreHorner** [comment]
I know that.  I've set the computer port to 0.0.0.-1 relative to what the laser cutter is set to (that's what gives the different error message).  Port on the laser cutter is set to 515.

**Comment by t-oster** [comment]
Dont confuse IP and Port. Try ping first. Both IPs have to be in the Same subnet

**Comment by LenoreHorner** [comment]
I know port and IP are separate.  I know the IPs have to be in the same subnet.  That's why I set the Helix to the default 192.168.3.4 and my computer to 192.168.3.3.  They still aren't communicating.  As far as I know, that means the port must be wrong (unless of course my cable has failed).  I can try ping when I get to school today.

**Comment by LenoreHorner** [comment]
Ping works fine.  (15 packets transmitted, 15 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 4.556/15.472/43.056/9.699 ms) I still get Error \ Connection timeout. Please see if the Lasercutter is switched on and connected to the network. \ SocketTimeoutException: connection timed out

**Comment by mgmax** [comment]
Please note thar at least on the Epilog Zing, you can't mix USB and Ethernet, and maybe even need to restart the lasercutter after switching from USB.

**Comment by LenoreHorner** [comment]
I have only the ethernet connected and I have restarted many times since I unplugged the USB.

**Comment by LenoreHorner** [comment]
I'm on a Helix not a Zing.

**Comment by t-oster** [comment]
Maybe Probe all open ports with nmap?

**Comment by LenoreHorner** [comment]
Here's what I get for ping and then for nmap.
--- 192.168.3.4 ping statistics ---
8 packets transmitted, 8 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 1.642/11.477/24.195/6.800 ms
MLH-MacBookAir:~ hornelen$ nmap -Pn 192.168.3.4
Starting Nmap 7.70 ( https://nmap.org ) at 2018-06-18 09:34 EDT
Nmap scan report for 192.168.3.4
Host is up (1.0s latency).
Not shown: 998 closed ports
PORT    STATE SERVICE
515/tcp open  printer
666/tcp open  doom

Nmap done: 1 IP address (1 host up) scanned in 140.21 seconds
Note how long the nmap scan took.  I think that's the problem.  I don't know why it's taking so much longer than ping but VisiCut is definitely timing out in less than 2 minutes.  It looks like 515 is the correct port so that's not the problem.  Just for kicks, I tried printing right after verifying with nmap.  I got Error \\ Exception: Timout.  Is there a way to change how long VisiCut will wait?  Is there something else I should try with Nmap?  (Note that I had to use nmap -Pn because plain nmap was also returning no results and suggests using -Pn in case pings are being blocked.)  Thanks for all your patience as I try to get this working.

**Comment by LenoreHorner** [comment]
I tried 
nmap -Pn -p 515 192.168.3.4
Starting Nmap 7.70 ( https://nmap.org ) at 2018-06-18 14:21 EDT
Nmap scan report for 192.168.3.4
Host is up (0.021s latency).

PORT    STATE SERVICE
515/tcp open  printer

Nmap done: 1 IP address (1 host up) scanned in 0.08 seconds
So if I tell it which port to look for, the timing is fine.  So it seems to me as if there is something different between ping, the way nmap pings and what nmap -Pn does that changes how the Helix responds.

**Comment by t-oster** [comment]
Do you have any Windows PCs/VMs to check if the original Epilog Printer Driver is working over Ethernet? Did you double check that you use the very same settings in VisiCut as for ping/nmap? What exactly does VisiCut say if you start it from command line and try to print?

**Comment by LenoreHorner** [comment]
We've never used the Helix with Windows and ethernet that I know of.  Since the Windows machine actually booted for something else today, I can try that tomorrow. 
What settings to I have control over besides IP and port?  I have only started VisiCut from the command-line script not directly from the command line.  I can check that tomorrow too.

**Comment by t-oster** [comment]
Just do be sure please post a screenshot of your VisiCut Lasercutter Configuration dialog

**Comment by LenoreHorner** [comment]
![screen shot 2018-06-19 at 10 42 36](https://user-images.githubusercontent.com/23015014/41604554-87aaac16-73ad-11e8-9f0b-12152f54328f.png)
Below is the feedback when I run from the command line.
java -Xms256m -Xmx1024m -jar Visicut 
java.lang.Exception: Timeout
	at com.t_oster.liblasercut.drivers.EpilogCutter.waitForResponse(EpilogCutter.java:156)
	at com.t_oster.liblasercut.drivers.EpilogCutter.waitForResponse(EpilogCutter.java:125)
	at com.t_oster.liblasercut.drivers.EpilogCutter.sendPjlJob(EpilogCutter.java:226)
	at com.t_oster.liblasercut.drivers.EpilogCutter.realSendJob(EpilogCutter.java:342)
	at com.t_oster.liblasercut.drivers.EpilogHelix.realSendJob(EpilogHelix.java:35)
	at com.t_oster.liblasercut.drivers.EpilogCutter.sendJob(EpilogCutter.java:400)
	at com.t_oster.liblasercut.drivers.EpilogHelix.sendJob(EpilogHelix.java:35)
	at com.t_oster.visicut.VisicutModel.sendJob(VisicutModel.java:782)
	at com.t_oster.visicut.gui.MainView$65.run(MainView.java:2244)
java.lang.Exception: Timeout
	at com.t_oster.liblasercut.drivers.EpilogCutter.waitForResponse(EpilogCutter.java:156)
	at com.t_oster.liblasercut.drivers.EpilogCutter.waitForResponse(EpilogCutter.java:125)
	at com.t_oster.liblasercut.drivers.EpilogCutter.sendPjlJob(EpilogCutter.java:226)
	at com.t_oster.liblasercut.drivers.EpilogCutter.realSendJob(EpilogCutter.java:342)
	at com.t_oster.liblasercut.drivers.EpilogHelix.realSendJob(EpilogHelix.java:35)
	at com.t_oster.liblasercut.drivers.EpilogCutter.sendJob(EpilogCutter.java:400)
	at com.t_oster.liblasercut.drivers.EpilogHelix.sendJob(EpilogHelix.java:35)
	at com.t_oster.visicut.VisicutModel.sendJob(VisicutModel.java:782)
	at com.t_oster.visicut.gui.MainView$65.run(MainView.java:2244)

**Comment by t-oster** [comment]
The connection is fine, it hangs when waiting for an answer here https://github.com/t-oster/LibLaserCut/blob/a677fc51386985bd0bf4210a6049c587ba77a33a/src/com/t_oster/liblasercut/drivers/EpilogCutter.java#L225. Maybe your firmware version is different from the other helixes which work with VisiCut? Or it is not configured for PJL mode? You should try the Windows Epilog driver and then try again or try to sniff the traffic with wireshark in order to spot the difference.

**Comment by LenoreHorner** [comment]
Ok, now I feel like a complete idiot.  The first day I was working on this, I carefully unplugged the USB cable to use the ethernet cable as instructed.  But then I plugged the USB back in for other people to use and forgot on all the other days to unplug it before plugging in the ethernet.  Now I can send jobs to the laser (but I didn't so something right about heights because the bed stayed too low and everything came out unfocussed and wrong.)  Thanks for all your patience.

**Comment by LenoreHorner** [comment]
To summarize for others who find this thread:
Use the cross-platform version on MacOS. (Use Get Info if necessary to tell Finder to run the script with Terminal (in Utilities folder under Applications). (Install current version of Java from Oracle's site if necessary.)
Unplug any USB cable plugged into your printer.

I guess now I can go back to seeing if I can get an app package running that will actually export contents from Inkscape to VisiCut.  
THANK YOU for making this software!!

**Comment by mgmax** [comment]
@LenoreHorner Please feel free to extend the manual you can find here: https://github.com/t-oster/VisiCut/wiki/VisiCut-manual
I added a note regarding the USB problem. I have no MacOS, so it would be cool if you could add information for Mac users what exactly they have to do to make it work.
