### ISSUE TITLE
Community channels

### ISSUE THREAD

**Issue by arthurwolf** [t-oster/VisiCut#498]
Hey everyone !

I wanted to ask questions without bothering the devs, but I can't find any other community channel other than these issues. Is there anywhere users ( and some devs ) just hang out and help each other ? IRC channel on freenode, Slack channel, mailing list, forum, social media, etc ?
If not I think it'd be of a lot of benefit.

Cheers !

**Comment by t-oster** [comment]
I quickly set up https://qa.visicut.org. Please register and publish this URL. Pull requests, which add this URL as the primary community channel e.g. on the gh-pages branch (visicut.org) etc are welcome

**Comment by TheAssassin** [comment]
For the record, this URL is dead.
