### ISSUE TITLE
Empty "Exemple" folder in the MacOS French version

### ISSUE THREAD

**Issue by waumand** [t-oster/VisiCut#502]
Hi makers !
With last Java 8 (version 201) with MacOS Mojave and 3 different Mac, in French, the "Exemple" folder is empty.

I can't use exemples to make some shapes :/

Any idea ?

<img width="1440" alt="Capture d’écran 2019-03-24 à 17 41 47" src="https://user-images.githubusercontent.com/6934787/54882832-659a1580-4e5e-11e9-8b28-3917da137a91.png">
<img width="488" alt="Capture d’écran 2019-03-24 à 17 43 07" src="https://user-images.githubusercontent.com/6934787/54882833-659a1580-4e5e-11e9-918e-a17997b8fea7.png">

**Comment by t-oster** [comment]
Wich settings did you download?

**Comment by waumand** [comment]
@t-oster when you say setting you speak about setting file ?
I use this one for my Fablab with the RS-1060L 3D printer
[visicut-1060.vcsettings.zip](https://github.com/t-oster/VisiCut/files/3000818/visicut-1060.vcsettings.zip)
http://robotseed.com/index.php?id_category=11&controller=category&id_lang=1

**Comment by t-oster** [comment]
I can confirm this. The examples included in the specific downloaded settings work, but the predefined examples are not found. Probably a path issue. I won't have time in the next two week though, but after that I will look into it.
