### ISSUE TITLE
Driver warnings should be sent on the fly.

### ISSUE THREAD

**Issue by tatarize** [t-oster/VisiCut#513]
The warnings are backed with a typical datastructure but are of type List<String>. You can render them to the screen instantly if you overload the interface there to pretend to be a list then add them to the UI as they are added.

I only bring this up because the K40 doesn't just process everything and send the job. It actually sends the job the entire time it's in that thread. It doesn't have crap for memory, just a little buffer. And if somethings go wrong like somebody unplugged the USB cable there's no way to say that to the user except within the ProgressListener which actually does update the UI on the fly.

Likewise the job send end message is not useful because that will happen after the job completes.

**Comment by t-oster** [comment]
Feel free to offer a pull request. The interfaces was designed with a job based lasercutter in mind, but since there are many interactive devices, we could change the interface (e.g. add a addWarning method to the progress listener or similar).
