### ISSUE TITLE
Windows 10 launcher doesn't work

### ISSUE THREAD

**Issue by Arrri** [t-oster/VisiCut#521]
I cannot run VisiCut.exe on Windows 10. I cannot get any logs either. When I try to run it nothing happens.

I am able to run VisiCut by executing .jar from platform independent zip.

**Comment by Arrri** [comment]
Java was installed with the visicut. It is in the PATH:

>java -version

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) Client VM (build 25.66-b18, mixed mode, sharing)

**Comment by t-oster** [comment]
If you run visicut.exe from the cmd it does not output anything?

**Comment by Arrri** [comment]
Yes, I tried different options and never got any logs or any output at all.

The command finishes immediately, there is a blank line and the prompt is
ready for the next command:

> VisiCut.exe

>

sob., 10 sie 2019, 22:06 użytkownik Thomas Oster <notifications@github.com>
napisał:

**Comment by Arrri** [comment]
![sc](https://user-images.githubusercontent.com/6017774/62837448-b83e6780-bc6f-11e9-807d-777adff44cc6.png)

**Comment by t-oster** [comment]
Hi, can you retry with the latest version. However I did not change anything. Which version did work last?

**Comment by Arrri** [comment]
Sure, I will.

I don't know this exact version (I will check it after work). About week ago I tried most of the available version and none of them worked for me. I started using jar from portable directly and I didn't have any problem with it.

I wanted to try inkscape plugin and I need exe version for that. Exe didn't work from the same portable version from which jar worked.

**Comment by Arrri** [comment]
Nothing changed.
![VisiCut](https://user-images.githubusercontent.com/6017774/62954463-bbf8f800-bdef-11e9-8b08-ddadc2cbcf35.png)

I tried versions:
1.7-310
1.8-75
1.8-80
1.8-90
1.8-92

Installer is unable to modify PATH env var but I've always used the default path and I then I manually added the path to PATH var:
PATH=....;C:\Program Files (x86)\VisiCut;...

**Comment by Kr4cker** [comment]
I got exactly the same error.
Another problem which is probably related to this is that the inkscape plugin is not working.
It is not possible to add or open a sketch to/in VisiCut.
I used also the newest version of 1.8-92.
The java version was installed during the VisiCut installation.

**Comment by mgmax** [comment]
I'm sorry but I am unable to reproduce this issue. I set up Windows 10 Pro in a VirtualBox VM with German language, installed Visicut and it starts correctly. Can you please tell me how to reproduce the bug, preferably on a clean installation? (You don't need a Windows license key for testing in a VM, just use the ISO from Microsoft and say "I dont have a product key", this will give you a few days of demo license for testing).

For reference, the launcher starts VisiCut with `javaw.exe -Xms256m -Xmx1024m -classpath ".;lib" -jar Visicut.jar --singleinstanceport 6543`

**Comment by mgmax** [comment]
Please test again with version 1.8-99, which includes its own Java runtime.

**Comment by Arrri** [comment]
I'll try to test it soon and let you know about the results.
*Alan Kutniewski*


niedz., 20 paź 2019 o 10:53 Max Gaukler <notifications@github.com>
napisał(a):

**Comment by Arrri** [comment]
I tested 1.8-99 and it works.

**Comment by Kr4cker** [comment]
Same here. Installed 1.8-99 direct over the older version.
Now it works with the windows launcher =)
Thank you very much
