### ISSUE TITLE
Leetro 6515 No x y But will datum ????

### ISSUE THREAD

**Issue by Steve1564** [t-oster/VisiCut#523]
Hi everyone...

Kinda out of ideas on this one... I have a laserscript ls1390

It wont XY but will datum... Keypad is fine and its the same from the PC 

Any ideas ?

Steve

**Comment by t-oster** [comment]
could you please explain more in detail what you mean? What does `XY` and `will datum` mean?

**Comment by mgmax** [comment]
Closing because the submitter did not respond for a longer time, and there is nothing we can do without a response.
