### ISSUE TITLE
Cleanup old issues

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisiCut#535]
There's a huge list of bugreports which refer to outdated VisiCut/Java versions and are therefore useless. A similar problem is if the submitter does not reply to questions, so the bug cannot be reproduced. I'd like to help by closing the respective issues, but don't have the permission for that.

(For private repositories, GitHub doesn't offer a full permission system. However, directly pushing to branches without a pull request can be prevented by using "Settings - Branches - Branch protection rules". For repositories under an organization account, there is a wide range of permissions, including the "Triage" level which allows managing issues but not pushing -- see https://help.github.com/en/articles/repository-permission-levels-for-an-organization . It is possible to create a free organization account and move a repository to that.)

**Comment by t-oster** [comment]
I added you to the colaborators. if this does not give you the permission, you can also just comment a list of issues prefixed with # so I can close them.

Thank you for all the work you put in VisiCut. If my current job would have any relation to lasercutting this project would process much faster, but unfortunately my spare time is very limited.
