### ISSUE TITLE
Weird behavior on Windows since Java11

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisiCut#538]
Since switching to Java11 (?), there are strange errors on Windows 10, especially in High-DPI setups:
![Screenshot_20191103_145623](https://user-images.githubusercontent.com/1520891/68086264-1b443280-fe4a-11e9-81de-bfad0286a5a8.png)
The screenshot is from my tests with a Virtualbox VM with 150% scaling enabled in the Windows display settings. This is not the only error (once I got one regarding TableModel, and once the preview did not react to changing the mapping), but the only one I could reliably reproduce. 

To reproduce, use Visicut with Fablab Berlin settings, open examples - basic - rectangle-20mm-green. Close Visicut.
Then it crashes about 2/10 times for the following: Open VisiCut, Files - recent files - rectangle-20mm-green.

My best guess would be that we have a huge threadsafety issue:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6888157
https://www.tutorialspoint.com/is-swing-thread-safe-in-java
https://docs.oracle.com/javase/tutorial/uiswing/concurrency/index.html

**Comment by t-oster** [comment]
Could not reproduce it on Linux with Debugger attached. Please try to run it from Netbeans with debugger and you can add a breakpoint for all null pointer exceptions (https://stackoverflow.com/questions/2669808/netbeans-how-do-i-break-on-a-nullpointerexception) you can then examine the threads and data involved, maybe this gives a hint.

I fear that thread safety was not really considered when I first wrote visicut, nor did I understand the whole swing worker thread concept....
