### ISSUE TITLE
1.9-13 and 1.9-12 download links broken

### ISSUE THREAD

**Issue by whatupant** [t-oster/VisiCut#548]
The download links for all the different flavors of version 1.9-13 and 1.9-12 seem to be broken.

For example, hitting this link from the downloads page: https://download.visicut.org/files/master/MacOSX/VisiCutMac-1.9-13-g5466b2e4+devel.zip

Results in:
Not Found
The requested URL /files/master/MacOSX/VisiCutMac-1.9-13-g5466b2e4+devel.zip was not found on this server.

Same for 1.9-12.

I'm having the same issue as reported in #544 and was hoping to test out a newer version on Mac.

**Comment by mgmax** [comment]
will be fixed by https://github.com/t-oster/VisicutBuilder/pull/6

**Comment by t-oster** [comment]
Links are fixed
