### ISSUE TITLE
wrong version number in VisiCut 1.9-35-g98e949b3

### ISSUE THREAD

**Issue by suschizu** [t-oster/VisiCut#560]
hello!
I've downloaded version 1.9-35-g98e949b3 but finder shows $VERSION instead
![image](https://user-images.githubusercontent.com/16004333/72193570-6bbbab80-340a-11ea-98b9-6d824388e32f.png)

**Comment by t-oster** [comment]
Does the splash screen show the correct version?

**Comment by t-oster** [comment]
I guess I somewhere forgot to update the info.plist....

**Comment by t-oster** [comment]
Does it work with the latest version?

**Comment by suschizu** [comment]
hey thomas! sorry for the late reply - and thanks - everything looks good now - great :)

![image](https://user-images.githubusercontent.com/16004333/72221902-278def80-355f-11ea-8bb1-0f290d2fa311.png)

**Comment by suschizu** [comment]
hey @t-oster - sorry for the late reply - and thanks! everything looks good - great - no more confusion :)
![image](https://user-images.githubusercontent.com/16004333/72221943-8bb0b380-355f-11ea-93d3-2ba12e57022d.png)
