### ISSUE TITLE
Download page offline - migrate to GitHub releases?

### ISSUE THREAD

**Issue by t-oster** [t-oster/VisiCut#578]
My server is down and the company is not answering.
Maybe this is n opportunity to migrate to CI automatically create a GitHub release for every tagged commit (https://docs.travis-ci.com/user/deployment/releases/).
I will try that tomorrow.
However I am not sure if there are any limitations on the number of releases or the size of the build artifacts....

**Comment by mgmax** [comment]
If it's too hard with travis, GitHub actions may be a viable alternative.

**Comment by t-oster** [comment]
@mgmax seems to work now. You just have to tag a commit and push it to master to trigger a release. I would recommend to use 1.9-xx as tag just counting upwards.

**Comment by t-oster** [comment]
download links should be updated soon
