### ISSUE TITLE
Visicut + ruida controller

### ISSUE THREAD

**Issue by ARKopp** [t-oster/VisiCut#597]
I am thinking to get a chinise laser with a ruida controller 6442S. Does Visicut work with this controler?

**Comment by mgmax** [comment]
Currently not. There is some ongoing development for certain Ruida controllers, you could possibly build upon that: https://github.com/t-oster/VisiCut/issues/404 https://github.com/t-oster/LibLaserCut/issues/105 https://github.com/t-oster/LibLaserCut/pull/134

**Comment by ARKopp** [comment]
but this would do the shop right ? https://github.com/jnweiger/inkscape-thunderlaser

**Comment by mgmax** [comment]
I don't know. It is supposed to be for the same lasercutter as the VisiCut driver under development. Not all Ruida boards are the same, so it may or may not work with the board you asked about. I would guess that smaller modifications may be required.

**Comment by ARKopp** [comment]
i will ask the developers if it works with the ruida board i want to get

Am Do., 7. Jan. 2021 um 16:03 Uhr schrieb Max Gaukler <
notifications@github.com>:
