### ISSUE TITLE
Y axis ruler fails when bottom left origin is active

### ISSUE THREAD

**Issue by danke-0x21** [t-oster/VisiCut#608]
Hi,
The left ruler (Y axis) won't show lower and upper digits when zooming in & when origin on the bottom left corner is activated.
Works fine when not zooming in or with origin on the default top left corner.

Tested on Win10 (1.9-83) and Debian (1.9-94)

Here a picture when zooming next to the origin point :
![image](https://user-images.githubusercontent.com/84600646/119197655-63f12a00-ba88-11eb-92be-3c58eedc4cfb.png)

**Comment by mgmax** [comment]
Thanks for reporting, I accidentally broke this last year. The fix will be in the next release :-)

**Comment by danke-0x21** [comment]
Thanks to you for fixing so fast.
