### ISSUE TITLE
Missing icons in Ubuntu 21.04

### ISSUE THREAD

**Issue by davedarko** [t-oster/VisiCut#613]
We recently moved from Windows to Ubuntu for our laser cutting computer at the xHain Hackspace. For some reason some icons, probably GTK related, are missing. Starting it from the terminal it was complaining about a missing module. Installing the "gtk canberra module" did not change the appearance. Changing icon themes with gnome-tweaks neither. Not sure what I should do next.

![Screenshot from 2021-08-28 16-03-56](https://user-images.githubusercontent.com/1286580/131222718-7ae4284d-c814-4cbd-8bce-21b8647edce3.png)
![Screenshot from 2021-08-28 17-19-04](https://user-images.githubusercontent.com/1286580/131222719-d12a6ca7-6ba1-4570-96c3-ed8326368c33.png)

**Comment by mgmax** [comment]
Does switching to Java 11 work for you? (See #614)

**Comment by mgmax** [comment]
Should be fixed in the next version (1.9-108 or so).
@t-oster can you please upload the new version?

**Comment by t-oster** [comment]
2min
