### ISSUE TITLE
Does not work with xstream 1.4.18

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisiCut#615]
With xstream 1.4.18, loading settings is completely broken.
As a workaround, I reverted to xstream 1.4.17 in commit 682fda85dc89ec5e085bdecf51b7bbce636e86da .
Updating xstream needs more work, as we need to set up an explicit list of classes that are allowed for deserialization. See https://x-stream.github.io/security.html#framework .

**Comment by t-oster** [comment]
see https://github.com/t-oster/VisiCut/pull/616
