### ISSUE TITLE
Travis CI build broken

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisiCut#617]
travis-ci.org has shut down. The same service is now available at travis-ci.com.
@t-oster As far as I know, you need to sign in at travis-ci.com, select a plan (User Icon - Settings - Plan - choose "Free"), and then enable the repositories using "Settings - Migrate".

**Comment by t-oster** [comment]
strange. I signed up and connected, but it shows all repositories except VisiCut....
Is it possible to show Gitlab-CI state in Github?

**Comment by t-oster** [comment]
got it working again.
