### ISSUE TITLE
New builds don't seem to work with LAOS Lasercutters

### ISSUE THREAD

**Issue by thinkl33t** [t-oster/VisiCut#629]
I have access to two LAOS lasercutters, one at Hackspace Manchester, and one at home.   Both running the latest version of laos.

We've noticed that on new versions of visicut (those from the visicut downloads page), what looks like completely blank files are being sent through to the laser cutter.  Symptoms are that when asked to run, the laser will start up the fans, extraction etc, then immediately end the job.  

I have inspected the simplecode files visicut is generating (by exporting them) and they seem to be correct.  Some files seem to be generated and sent through correctly - notably the finger-box example works fine.

We have triaged all the visicut versions we could get our hands on, on debian and macos, and found the following:

* 1.8-103 works fine (we had this version lying around)
* 1.9-61 works fine (same)
* 1.9-70 works fine (from the github releases page)
* 1.9-113 doesn't work
* 1.9-111 doesn't work

**Comment by mgmax** [comment]
Is this the issue? https://github.com/t-oster/LibLaserCut/issues/131
Then the expected symptom would be that it does not work for all files.

You could try with network sniffing software (e.g., wireshark) to check what's sent to the cutter and check if the length roughly matches the simplecode file.

**Comment by thinkl33t** [comment]
![Screenshot from 2021-12-15 15-23-14](https://user-images.githubusercontent.com/1016780/146214506-e816c4cd-6c62-4c94-b90b-aa4b5aaa2917.png)

![Screenshot from 2021-12-15 15-23-43](https://user-images.githubusercontent.com/1016780/146214517-6c5ce359-4688-47d9-aaa9-217f50719604.png)

**Comment by thinkl33t** [comment]
Attached is a zip of the pcapng file if you want to look - this is using visicut 1.9-135

[visicut-1.9-135.zip](https://github.com/t-oster/VisiCut/files/7720687/visicut-1.9-135.zip)

**Comment by thinkl33t** [comment]
Same file, 1.9-41 - worked fine

![Screenshot from 2021-12-15 15-48-18](https://user-images.githubusercontent.com/1016780/146218636-87734ba3-7baa-4110-9faf-97c2684ad849.png)

[visicut-1.9-41.zip](https://github.com/t-oster/VisiCut/files/7720811/visicut-1.9-41.zip)

**Comment by t-oster** [comment]
Can you set up a dev environment and do a git bisect in LibLaserCut in order to find the commit, which introduced that problem?

**Comment by mgmax** [comment]
Does it make a difference if you restart VisiCut before every laser job? We sometimes had bugs regarding the initialization, where the laser driver only worked correctly for the first job.

**Comment by thinkl33t** [comment]
Just tried -135 again with wireshark doing its thing, same behaviour on the first attempt as subsequent attempts.

**Comment by mgmax** [comment]
should be fixed in the next release, same issue as https://github.com/t-oster/VisiCut/issues/647 - files only work if they are big enough (and/or if you have random luck with the Java garbage collector timing)
