### ISSUE TITLE
Parameters for laser power not taken in account

### ISSUE THREAD

**Issue by Jorgininho** [t-oster/VisiCut#646]
Hello, I face an issue with visicut when the parameters for laser aren't taken in account.
I use the version 1.9-142 on ubuntu 22.04.

So if I use for laser settings a power of 50, I get in the gcode a power of 0 ("S0", when I expect "S0.5")
If I want a power of 51%, I get full power ("S1" in gcode when I expect "S0.51")
I got the same result if I ask to "cut" or to "mark" the stroke

**Comment by t-oster** [comment]
Maybe the same as #644 ?

**Comment by Jorgininho** [comment]
indeed it is, workaround worked well, thanks !

**Comment by t-oster** [comment]
Did you create your settings with this version or did it work before an an update broke it? We should make sure the setting has a useful default and this default is applied when loading settings from a previous version

**Comment by Jorgininho** [comment]
I use configuration for my fablab "le bocal, chemillé..."
indeed, if you can change this settings to have at least 3 digits for the laser power by default for our fablab would be great !

**Comment by t-oster** [comment]
Well if you correct and save your settings for your fablab it should work. However visicut should default to 3 digits when the setting is not present instead of 0

**Comment by mgmax** [comment]
I tried it with the latest Visicut version and do not have the problem. Please download the settings again, Visicut may have remembered the wrong value locally.
