### ISSUE TITLE
Camera Calibration sends empty Job File to Laser Cutter.

### ISSUE THREAD

**Issue by mariolukas** [t-oster/VisiCut#647]
VisiCut Version : 1.9-141
Operating System MacOS: Monterey 12.2 
System: MacBook Pro (M1)
LaserCutter: LAOS based.

I am trying to calibrate my camera.  Installed VisCam successfully. I am getting a camera image etc. 

My issue: 

- clicking the send button on the camera calibration dialog. 
- sending is confirmed
- job arrived at the laser cutter and is showing up on the display
- confirming to run the job with the laser cutter controls ( OK Button)
- laser cutter is homing
- nothing else happens

Regular cut and mark jobs are working great. I have checked the job data on the SD card. It seems that visicut is sending empty jobs. 

I started with a fresh VisiCut installation and deleted all the profiles and custom configurations before i installed VisiCut again.

**Comment by mgmax** [comment]
I found the issue, working on it

**Comment by mgmax** [comment]
@t-oster can you please trigger a build? Travis CI still seems broken

**Comment by mgmax** [comment]
The new version is online, please give feedback whether 1.9-146 works

**Comment by mariolukas** [comment]
Thank you, it seems to work now.
