### ISSUE TITLE
Add FabLabs La Fabrique Roche aux Fées LaserCut

### ISSUE THREAD

**Issue by LaFabrique35** [t-oster/VisiCut#649]
Hello,
Can you add my lab default settings to Visicut ?
("France, La Fabrique Roche Aux Fées", "https://github.com/LaFabrique35/visicut-settings/archive/master.zip")

Thank's !

**Comment by mgmax** [comment]
Will be in the next release. Greetings from Erlangen, the partner city of Rennes near your lab :-)

**Comment by LaFabrique35** [comment]
Thank you ! Greetings too ;)
