### ISSUE TITLE
incorrect Esc for width, with Epilog ZING

### ISSUE THREAD

**Issue by minniR2D2** [t-oster/VisiCut#656]
with the driver Epilog ZING 
and the mapping "engraving (red) & cut (green)" an incorrect code is generated
for height (Esc*r#T) and width (Esc*r#S).

with the mapping "cut all" everything is ok.

**Comment by mgmax** [comment]
Why do you think it is wrong? Can you give an example of the output and the expected correct output from another application (e.g. Epilog Windows printer driver)?

**Comment by mgmax** [comment]
Closing due to lack of response. Please answer and reopen if you have more information.
