### ISSUE TITLE
Download page outdated

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisiCut#663]
https://download.visicut.org/ doesn't have the latest commit even after two hours of waiting time.

**Comment by mgmax** [comment]
@t-oster it would also be good if you could check whether the build container is up to date. It looks like in the latest build the logo wasn't rendered correctly, though this should have been fixed in the latest VisicutBuilder.

**Comment by t-oster** [comment]
I triggered the build. There is no new docker image for the builder but I have to check tomorrow how to improve this

**Comment by mgmax** [comment]
In the latest build, the docker image is still outdated, which makes the logo look suboptimal.

**Comment by t-oster** [comment]
The gitlab mirror (https://gitlab.com/t-oster/visicutbuildservice) was outdated. I am building the image right now, should be fixed soon.

**Comment by t-oster** [comment]
does not seem to build https://gitlab.com/t-oster/visicutbuildservice/-/jobs/4177019752

**Comment by t-oster** [comment]
nevermind, seems to be a space issue on gitlab (the image is 1.4GB). I built it locally and pushed it.
I did a fresh build of the 1.9-173 versions.
