### ISSUE TITLE
inkscape viscut issues

### ISSUE THREAD

**Issue by hirilpatel** [t-oster/VisiCut#664]
Hello,

I dont know if this issue has already been reported but, after a while visicut extension from inkscape stopped working. I am not a computer person here so can someone help me out?

Here is the photo of error message. Please keep in mind that i didn't updated not the computer not the inkscape or visicut.
![IMG-1004](https://user-images.githubusercontent.com/58297010/214041480-1eba1a45-d204-4870-9c1b-8e6a55ae9c5c.JPG)

**Comment by mgmax** [comment]
Well, if you changed nothing, then it can't stop working :-D

Please try reinstalling the Inkscape extension using the Visicut menu (Extras - Install Inkscape extension).

Does the problem also happen on another computer?

**Comment by mgmax** [comment]
Closing because there was no response. Please respond if you have more information.

**Comment by hirilpatel** [comment]
Hello,

Sorry for no response. I am not currently in the office and won't be till
end of march hence can't do what you suggest. Can you please keep this
issue open?

I can only check after march
