### ISSUE TITLE
command-line access to visicut?

### ISSUE THREAD

**Issue by valkyriesavage** [t-oster/VisiCut#665]
I can't find anything in the manuals about this, but is there a way to summon visicut from the commandline? I'd like to be able to give it a file with cut parameters, an svg to cut, a laser bed location to cut it at, and whatever is necessary to talk with my laser; this would help with fiddling with settings.

**Comment by valkyriesavage** [comment]
ok, I found the docs you mentioned, but it seems that it's ignoring my arguments on commandline (I'm using the [instructions I found](https://github.com/t-oster/VisiCut/wiki/Development:-Running-from-commandline)).

<img width="625" alt="image" src="https://user-images.githubusercontent.com/594129/215575883-37bb652e-1a98-458c-acfe-aff68bb3c126.png">

I did try to do platform-independent installation (it's in my Applications folder), but my computer is not finding a `visicut` command in terminal.

**Comment by t-oster** [comment]
Maybe the VisiCut.MacOS does not pass through the command line arguments. Open it in a text editor and add `"$@"` in the line with VisiCut.jar

**Comment by valkyriesavage** [comment]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/594129/215580945-40591d83-ee7d-4fb9-8a4a-f797fb930617.png">
it seems to already have that?

**Comment by mgmax** [comment]
On Linux `visicut -h` shows the help and then exits. The Linux launcher does something similar.
So I guess the script you are showing is not the one that is actually called.

**Comment by valkyriesavage** [comment]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/594129/215782589-c18210a7-e8e8-4aa4-9f5f-d2738fc6084e.png">

**Comment by t-oster** [comment]
Could you try to execute the java line directly (replacing $DIR with '.' and $@ with -h?

**Comment by valkyriesavage** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/594129/216094433-3e363aa7-0b16-4887-9c0a-a82857c40a2e.png">

It now just exits, but doesn't seem to print to STDOUT. I also tried removing all the quotes, and the same thing happened:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/594129/216094826-1a6955a9-ed13-4205-ae93-4594e20065f0.png">

**Comment by valkyriesavage** [comment]
hmm... ok, it seems that I don't have a java runtime, and running that `java` command bare gets me complaints. do I have to have that to run on commandline? I'll go install it and try that.

**Comment by valkyriesavage** [comment]
🤦🏼‍♀️ now I'm getting an error that the jar file shipped in the release is too new for my fresh java installation
<img width="627" alt="image" src="https://user-images.githubusercontent.com/594129/216096922-cdb047d6-db95-4e5e-ad8a-920d3fe69cf2.png">
I'll go set up the dev compilation stuff

**Comment by valkyriesavage** [comment]
NetBeans is not cooperating at all, so fingers crossed there is a solution that isn't "compile from scratch to run on commandline"

**Comment by t-oster** [comment]
Does it work with the open command (second line without java?)

**Comment by t-oster** [comment]
The correct java version is included in the osx version

**Comment by mgmax** [comment]
Closing due to lack of response. Feel free to answer and reopen if you can provide more information.
