### ISSUE TITLE
Set up CI/CD completely with GitHub actions

### ISSUE THREAD

**Issue by TheAssassin** [t-oster/VisiCut#670]
To make development easier and allow contributors to test their changes in the real world before they send PRs, I would like to move CI/CD completely to GitHub actions. This would further allow for continuously deploying VisiCut in the form of a moving tag for which a prerelease can be created (this is what many AppImages do for instance, and the AppImage community provides tools that make this very easy).

In case you feel uncomfortable sharing secrets with GitHub (e.g., for code signing), you could set up a custom runner or perform the final steps on other private infrastructure. Both GitHub actions and any other CI/CD system should share the same scripts.

**Comment by mgmax** [comment]
I agree. Feel free to do so. 🙂 https://github.com/t-oster/VisicutBuilder should be a good starting point for the build environment/Docker container.

The visicut repo already contains "distribute.sh" which does 95% of all the building. It only lacks a few details such as the bundled Windows EXE for autotrace. These remaining 5% should be moved over from VisicutBuilder.

**Comment by TheAssassin** [comment]
I already rewrote most of `distribute.sh` (just didn't get to creating a PR) to make it more usable and include the AppImage build in it.

**Comment by TheAssassin** [comment]
#671 introduced a prototype Docker based build system based on the old AppImage-specific Dockerfile. Ideally, this will replace other Docker images to avoid redundancies.

**Comment by mgmax** [comment]
related: https://github.com/t-oster/VisiCut/pull/680

**Comment by TheAssassin** [comment]
PR available in #710.
