### ISSUE TITLE
github Releases is outdated

### ISSUE THREAD

**Issue by jnweiger** [t-oster/VisiCut#698]
https://github.com/t-oster/VisiCut/releases
currently advertises version 1.9-73 dated May 2020 - this is very old, and leaves wrong the impression, that the project requires compiling the code from master before using it.

I'd suggest to either or
1) Make one final dummy release (just a tag, no artefacts) with description: VisiCut releases are currently not uploaded to github. Please visit https://download.visicut.org
2) Make the build machinery at download.viscut.org also push to github.
3) Disable github releases entriely.

**Comment by mgmax** [comment]
Fixed for now. For the rest see #670.
