### ISSUE TITLE
Docu? daemonize.py in inkscape_extension obsolete?

### ISSUE THREAD

**Issue by drmpjz** [t-oster/VisiCut#700]
Various documents concerning the extension as well as the current versions of install.sh and PKGBUILD in the tools/inkscape_extension/ directory reference the script daemonize.py.

This script is not part of the repository on github and is also not generated during the build process.

Is it actually still required? If so, where to find it. If not, it would be nice to at least update install.sh and PKGBUILD to no longer reference the (obsolete?) file.

**Comment by mgmax** [comment]
No, daemonize.py is no longer required.
I assume the PKGBUILD and install.sh files of the Inkscape extension are not used and can also be removed.
You can install the Inkscape extension via Extras the menu of VisiCut. For some platforms/distributions we also automatically install it system-wide as part of the VisiCut package/installer.

**Comment by drmpjz** [comment]
Should I create a pull request to remove the files or will you?

**Comment by mgmax** [comment]
Feel free to create a PR, thanks :-)

**Comment by drmpjz** [comment]
PR  open :-)
