### ISSUE TITLE
Download server outdated

### ISSUE THREAD

**Issue by mgmax** [t-oster/VisiCut#728]
@t-oster the download.visicut.org server seems to be outdated. Can you please check?

Or if that doesn't work we could also shut it down and redirect to https://github.com/t-oster/VisiCut/releases .

**Comment by t-oster** [comment]
It does redirect 301 to github now. Feel free to update all the links in the documentation etc. There is no sense in keeping the download page, as long as github releases work.

**Comment by mgmax** [comment]
Thanks :-)
